domains:
  ccs-12km:
    projection:
      type: LambertConformal
      kwargs:
        central_longitude: -19
        central_latitude: 65
        standard_parallels: [63, 67]

variables:
  FG_CO2:
    cmap: "viridis"
    dc: 0.1
    cmin: -5.0
    cmax: 5.0
  pCO2SURF:
    cmap: "viridis"
    dc: 5
    cmin: 300
    cmax: 425